/**
 * Company admin — company-wide reports browser (scoped routes under `/company/reports`).
 *
 * Read-only view of Detailed Project Reports generated by users in the
 * logged-in company admin's company. Intentionally does NOT expose any
 * mutation actions (no approve / reject / upload revised / delete). The
 * backend is already company-scoped for this role, so the component only
 * reads from `/admin-reports*` endpoints and renders a trimmed UI.
 */

import React, { useEffect, useState, useCallback } from 'react';
import {
  FileText,
  Eye,
  Download,
  Search,
  Filter,
  RefreshCw,
  Clock,
  CheckCircle,
  XCircle,
  AlertCircle,
  ChevronDown,
  ChevronUp,
  FileSpreadsheet,
  User,
  Loader2,
  X,
  Settings,
  MessageSquare
} from 'lucide-react';
import { AdminLayout } from '../../components/layouts';
import { useAuth } from '../../hooks';
import api from '../../api/apiClient';
import toast from 'react-hot-toast';

const CompanyAdminReportsPage = () => {
  const { user } = useAuth();
  const [reports, setReports] = useState([]);
  const [stats, setStats] = useState({
    pending: 0,
    under_review: 0,
    approved: 0,
    rejected: 0,
    total: 0
  });
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('');
  const [expandedReport, setExpandedReport] = useState(null);
  const [pagination, setPagination] = useState({ current_page: 1, total_pages: 1, total_count: 0 });

  const [searchQuery, setSearchQuery] = useState('');
  const [reportType, setReportType] = useState(''); // backend filter: report_type
  const [reportTypeOptions, setReportTypeOptions] = useState([]);
  const [dateRange, setDateRange] = useState({ start: '', end: '' });
  const [showFilters, setShowFilters] = useState(false);

  const [selectedReport, setSelectedReport] = useState(null);
  const [showPdfViewer, setShowPdfViewer] = useState(false);
  const [pdfBlobUrl, setPdfBlobUrl] = useState(null);
  const [loadingPdf, setLoadingPdf] = useState(false);

  const fetchStats = useCallback(async () => {
    try {
      const response = await api.get('/admin-reports/stats');
      setStats(response.data?.data || {});
    } catch (error) {
      console.error('Error fetching company report stats:', error);
    }
  }, []);

  const fetchReportTypes = useCallback(async () => {
    try {
      const response = await api.get('/admin-reports/meta/report-types');
      const types = response.data?.data?.report_types || [];
      const templateIds = response.data?.data?.template_ids || [];
      const merged = Array.from(new Set([...(types || []), ...(templateIds || [])].filter(Boolean).map(String))).sort(
        (a, b) => a.localeCompare(b)
      );
      setReportTypeOptions(merged);
    } catch (error) {
      // Non-blocking: still allow search by text
      console.error('Error fetching report types:', error);
    }
  }, []);

  const fetchReports = useCallback(async (page = 1) => {
    try {
      setLoading(true);
      const params = new URLSearchParams();
      if (activeTab) params.append('status', activeTab);
      if (reportType) params.append('report_type', reportType);
      if (searchQuery) params.append('search', searchQuery);
      if (dateRange.start) params.append('start_date', dateRange.start);
      if (dateRange.end) params.append('end_date', dateRange.end);
      params.append('page', page);
      params.append('limit', 20);

      const response = await api.get(`/admin-reports?${params.toString()}`);
      setReports(response.data?.data?.reports || []);
      setPagination(response.data?.data?.pagination || { current_page: 1, total_pages: 1 });
    } catch (error) {
      console.error('Error fetching reports:', error);
      toast.error('Failed to fetch reports');
    } finally {
      setLoading(false);
    }
  }, [activeTab, reportType, searchQuery, dateRange]);

  useEffect(() => {
    fetchStats();
    fetchReports();
    fetchReportTypes();
  }, [fetchStats, fetchReports, fetchReportTypes]);

  // Cleanup blob URL when modal closes / component unmounts
  useEffect(() => {
    return () => {
      if (pdfBlobUrl) {
        URL.revokeObjectURL(pdfBlobUrl);
      }
    };
  }, [pdfBlobUrl]);

  const handleSearch = (e) => {
    e.preventDefault();
    fetchReports(1);
  };

  const handleViewPdf = async (report) => {
    setSelectedReport(report);
    setShowPdfViewer(true);
    setLoadingPdf(true);

    try {
      const response = await api.get(`/admin-reports/${report._id}/pdf?inline=true`, {
        responseType: 'blob'
      });
      const blob = new Blob([response.data], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      setPdfBlobUrl(url);
    } catch (error) {
      console.error('Error loading PDF:', error);
      toast.error('Failed to load PDF preview');
      setShowPdfViewer(false);
    } finally {
      setLoadingPdf(false);
    }
  };

  const handleDownloadExcel = async (report) => {
    try {
      const response = await api.get(`/admin-reports/${report._id}/excel`, {
        responseType: 'blob'
      });
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `${report.title || 'report'}.xlsx`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
      toast.success('Excel downloaded');
    } catch (error) {
      console.error('Error downloading Excel:', error);
      toast.error('Failed to download Excel file');
    }
  };

  const handleDownloadPdf = async () => {
    if (!selectedReport) return;
    try {
      const response = await api.get(`/admin-reports/${selectedReport._id}/pdf`, {
        responseType: 'blob'
      });
      const blob = new Blob([response.data], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${selectedReport.title || 'report'}.pdf`;
      link.click();
      URL.revokeObjectURL(url);
      toast.success('PDF downloaded successfully');
    } catch (error) {
      console.error('PDF download failed:', error);
      toast.error(
        typeof error === 'string' ? error : error?.message || 'Failed to download PDF'
      );
    }
  };

  const closePdfViewer = () => {
    setShowPdfViewer(false);
    setSelectedReport(null);
    if (pdfBlobUrl) {
      URL.revokeObjectURL(pdfBlobUrl);
      setPdfBlobUrl(null);
    }
  };

  const getStatusBadge = (status) => {
    const statusConfig = {
      pending_validation: { bg: 'bg-yellow-100', text: 'text-yellow-700', label: 'Pending' },
      under_review: { bg: 'bg-purple-100', text: 'text-purple-700', label: 'Under Validation for CA' },
      approved: { bg: 'bg-green-100', text: 'text-green-700', label: 'Validated by CA' },
      rejected: { bg: 'bg-red-100', text: 'text-red-700', label: 'Rejected' },
      draft: { bg: 'bg-gray-100', text: 'text-gray-600', label: 'Draft' }
    };
    const config = statusConfig[status] || statusConfig.draft;
    return (
      <span className={`px-2 py-1 text-xs font-medium rounded-full ${config.bg} ${config.text}`}>
        {config.label}
      </span>
    );
  };

  return (
    <AdminLayout>
      <div className="p-6 max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6">
          <div>
            <h1 className="text-2xl font-bold text-gray-800">Company Reports</h1>
            <p className="text-gray-500 mt-1">
              View Detailed Project Reports generated by users in your company.
            </p>
            {user?.companyId && (
              <p className="text-xs text-gray-400 mt-1">
                Read-only view • scoped to your company
              </p>
            )}
          </div>
          <button
            onClick={() => { fetchReports(); fetchStats(); }}
            className="flex items-center px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors"
          >
            <RefreshCw size={18} className="mr-2" />
            Refresh
          </button>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-6">
          <button
            type="button"
            onClick={() => setActiveTab('pending_validation')}
            className={`bg-white rounded-xl p-4 shadow-sm border-2 cursor-pointer transition-all text-left ${
              activeTab === 'pending_validation' ? 'border-yellow-500' : 'border-transparent hover:border-yellow-200'
            }`}
          >
            <div className="flex items-center justify-between">
              <Clock className="text-yellow-500" size={24} />
              <span className="text-2xl font-bold text-gray-800">{stats.pending || 0}</span>
            </div>
            <p className="text-sm text-gray-600 mt-2">Pending</p>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('under_review')}
            className={`bg-white rounded-xl p-4 shadow-sm border-2 cursor-pointer transition-all text-left ${
              activeTab === 'under_review' ? 'border-[#7e22ce]' : 'border-transparent hover:border-purple-200'
            }`}
          >
            <div className="flex items-center justify-between">
              <AlertCircle className="text-purple-500" size={24} />
              <span className="text-2xl font-bold text-gray-800">{stats.under_review || 0}</span>
            </div>
            <p className="text-sm text-gray-600 mt-2">Under Review</p>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('approved')}
            className={`bg-white rounded-xl p-4 shadow-sm border-2 cursor-pointer transition-all text-left ${
              activeTab === 'approved' ? 'border-green-500' : 'border-transparent hover:border-green-200'
            }`}
          >
            <div className="flex items-center justify-between">
              <CheckCircle className="text-green-500" size={24} />
              <span className="text-2xl font-bold text-gray-800">{stats.approved || 0}</span>
            </div>
            <p className="text-sm text-gray-600 mt-2">Approved</p>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('rejected')}
            className={`bg-white rounded-xl p-4 shadow-sm border-2 cursor-pointer transition-all text-left ${
              activeTab === 'rejected' ? 'border-red-500' : 'border-transparent hover:border-red-200'
            }`}
          >
            <div className="flex items-center justify-between">
              <XCircle className="text-red-500" size={24} />
              <span className="text-2xl font-bold text-gray-800">{stats.rejected || 0}</span>
            </div>
            <p className="text-sm text-gray-600 mt-2">Rejected</p>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('')}
            className={`bg-white rounded-xl p-4 shadow-sm border-2 cursor-pointer transition-all text-left ${
              activeTab === '' ? 'border-purple-500' : 'border-transparent hover:border-purple-200'
            }`}
          >
            <div className="flex items-center justify-between">
              <FileText className="text-purple-500" size={24} />
              <span className="text-2xl font-bold text-gray-800">{stats.total || 0}</span>
            </div>
            <p className="text-sm text-gray-600 mt-2">Total</p>
          </button>
        </div>

        {/* Search and Filters */}
        <div className="bg-white rounded-xl shadow-sm p-4 mb-6">
          <form onSubmit={handleSearch} className="flex flex-col sm:flex-row gap-4">
            <div className="sm:w-56">
              <select
                value={reportType}
                onChange={(e) => setReportType(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent bg-white"
                title="Filter by report type"
              >
                <option value="">All Types</option>
                {reportTypeOptions.map((opt) => (
                  <option key={opt} value={opt}>
                    {opt}
                  </option>
                ))}
              </select>
            </div>
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search by applicant name or title..."
                className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
              />
            </div>
            <button
              type="button"
              onClick={() => setShowFilters(!showFilters)}
              className="flex items-center px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50"
            >
              <Filter size={18} className="mr-2" />
              Filters
              {showFilters ? <ChevronUp size={16} className="ml-2" /> : <ChevronDown size={16} className="ml-2" />}
            </button>
            <button
              type="submit"
              className="px-6 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700"
            >
              Search
            </button>
          </form>

          {showFilters && (
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-4 pt-4 border-t border-gray-200">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Start Date</label>
                <input
                  type="date"
                  value={dateRange.start}
                  onChange={(e) => setDateRange(prev => ({ ...prev, start: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">End Date</label>
                <input
                  type="date"
                  value={dateRange.end}
                  onChange={(e) => setDateRange(prev => ({ ...prev, end: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500"
                />
              </div>
              <div className="flex items-end">
                <button
                  type="button"
                  onClick={() => { setDateRange({ start: '', end: '' }); setSearchQuery(''); setReportType(''); }}
                  className="px-4 py-2 text-gray-600 hover:text-gray-800"
                >
                  Clear Filters
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Reports List */}
        <div className="bg-white rounded-xl shadow-sm overflow-hidden">
          {loading ? (
            <div className="flex items-center justify-center py-20">
              <Loader2 className="animate-spin text-purple-600" size={40} />
            </div>
          ) : reports.length === 0 ? (
            <div className="text-center py-20">
              <FileText className="mx-auto text-gray-300" size={60} />
              <p className="text-gray-500 mt-4">No reports found for your company</p>
            </div>
          ) : (
            <>
              {/* Table Header */}
              <div className="bg-gray-50 px-6 py-3 border-b border-gray-200 hidden md:grid grid-cols-12 gap-4 text-sm font-medium text-gray-600">
                <div className="col-span-4">Report</div>
                <div className="col-span-2">User</div>
                <div className="col-span-2">Date</div>
                <div className="col-span-2">Status</div>
                <div className="col-span-2 text-right">Actions</div>
              </div>

              {/* Report Rows */}
              {reports.map((report) => (
                <div key={report._id} className="border-b border-gray-100 last:border-0">
                  <div className="px-6 py-4 grid grid-cols-1 md:grid-cols-12 gap-4 items-center hover:bg-gray-50">
                    {/* Report Info */}
                    <div className="col-span-4 min-w-0">
                      <h3 className="font-medium text-gray-800 truncate" title={report.title}>{report.title}</h3>
                      <div className="flex items-center gap-2 mt-1">
                        <span
                          className="text-xs px-2 py-0.5 bg-purple-100 text-purple-700 rounded-full truncate"
                          title={report.templateId || report.report_type}
                        >
                          {report.templateId || report.report_type}
                        </span>
                        {report.client_name && (
                          <span className="text-xs text-gray-500 truncate" title={report.client_name}>
                            • {report.client_name}
                          </span>
                        )}
                      </div>
                    </div>

                    {/* User */}
                    <div className="col-span-2 min-w-0">
                      <p className="text-sm font-medium text-gray-800 truncate" title={report.user_id?.name || 'Unknown'}>
                        {report.user_id?.name || 'Unknown'}
                      </p>
                      <p className="text-xs text-gray-500 truncate" title={report.user_id?.email}>
                        {report.user_id?.email}
                      </p>
                    </div>

                    {/* Date */}
                    <div className="col-span-2">
                      <p className="text-sm text-gray-600">
                        {new Date(report.createdAt).toLocaleDateString('en-IN', { dateStyle: 'medium' })}
                      </p>
                      <p className="text-xs text-gray-400">
                        {new Date(report.createdAt).toLocaleTimeString('en-IN', { timeStyle: 'short' })}
                      </p>
                    </div>

                    {/* Status */}
                    <div className="col-span-2">
                      {getStatusBadge(report.validation_status)}
                    </div>

                    {/* Actions — VIEW ONLY */}
                    <div className="col-span-2 flex items-center justify-end gap-2">
                      {report.pdf_file_url && (
                        <button
                          type="button"
                          onClick={() => handleViewPdf(report)}
                          className="p-2 text-[#7e22ce] hover:bg-purple-50 rounded-lg transition-colors"
                          title="View PDF"
                        >
                          <Eye size={18} />
                        </button>
                      )}

                      <button
                        type="button"
                        onClick={() => handleDownloadExcel(report)}
                        className="p-2 text-green-600 hover:bg-green-50 rounded-lg transition-colors"
                        title="Download Excel"
                      >
                        <FileSpreadsheet size={18} />
                      </button>

                      <button
                        type="button"
                        onClick={() => setExpandedReport(expandedReport === report._id ? null : report._id)}
                        className="p-2 text-gray-500 hover:bg-gray-100 rounded-lg transition-colors"
                        title={expandedReport === report._id ? 'Hide details' : 'Show details'}
                      >
                        {expandedReport === report._id ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                      </button>
                    </div>
                  </div>

                  {/* Expanded Details */}
                  {expandedReport === report._id && (
                    <div className="px-6 py-4 bg-gray-50 border-t border-gray-200">
                      <div className={`grid grid-cols-1 gap-6 ${report.user_comment ? 'md:grid-cols-4' : 'md:grid-cols-3'}`}>
                        <div>
                          <h4 className="text-sm font-medium text-gray-700 mb-2 flex items-center">
                            <User size={16} className="mr-2" />
                            User Details
                          </h4>
                          <div className="space-y-1 text-sm">
                            <p><span className="text-gray-500">Name:</span> {report.user_id?.name}</p>
                            <p><span className="text-gray-500">Email:</span> {report.user_id?.email}</p>
                            <p><span className="text-gray-500">Phone:</span> {report.user_id?.phone || 'N/A'}</p>
                            <p><span className="text-gray-500">Role:</span> {report.user_id?.role}</p>
                          </div>
                        </div>

                        <div>
                          <h4 className="text-sm font-medium text-gray-700 mb-2 flex items-center">
                            <FileText size={16} className="mr-2" />
                            Report Details
                          </h4>
                          <div className="space-y-1 text-sm">
                            <p><span className="text-gray-500">Template:</span> {report.templateId}</p>
                            <p><span className="text-gray-500">Type:</span> {report.report_type || 'N/A'}</p>
                            <p><span className="text-gray-500">Client:</span> {report.client_name || 'N/A'}</p>
                            <p>
                              <span className="text-gray-500">Payment:</span>
                              <span className={`ml-1 ${report.payment?.status === 'completed' ? 'text-green-600' : 'text-yellow-600'}`}>
                                {report.payment?.status || 'N/A'}
                              </span>
                            </p>
                          </div>
                        </div>

                        <div>
                          <h4 className="text-sm font-medium text-gray-700 mb-2 flex items-center">
                            <CheckCircle size={16} className="mr-2" />
                            Validation Info
                          </h4>
                          <div className="space-y-1 text-sm">
                            <p><span className="text-gray-500">Status:</span> {report.validation_status}</p>
                            {report.validated_by && (
                              <p>
                                <span className="text-gray-500">Validated By:</span>{' '}
                                {report.validated_by?.name}
                              </p>
                            )}
                            {report.validated_at && (
                              <p>
                                <span className="text-gray-500">Validated At:</span>{' '}
                                {new Date(report.validated_at).toLocaleString('en-IN')}
                              </p>
                            )}
                            {report.rejection_reason && (
                              <p className="text-red-600">
                                <span className="text-gray-500">Reason:</span> {report.rejection_reason}
                              </p>
                            )}
                          </div>
                        </div>

                        {/* User Comment */}
                        {report.user_comment && (
                          <div>
                            <h4 className="text-sm font-medium text-gray-700 mb-2 flex items-center">
                              <MessageSquare size={16} className="mr-2" />
                              User Comment
                            </h4>
                            <div className="space-y-1 text-sm bg-white p-3 rounded-lg border border-gray-200 min-h-[80px]">
                              <p className="text-gray-700 whitespace-pre-wrap">{report.user_comment}</p>
                            </div>
                          </div>
                        )}

                        {(report.requested_sheets?.length > 0 || report.analysis_options) && (
                          <div className={`col-span-1 mt-4 pt-4 border-t border-gray-200 ${report.user_comment ? 'md:col-span-4' : 'md:col-span-3'}`}>
                            <h4 className="text-sm font-medium text-gray-700 mb-3 flex items-center">
                              <Settings size={16} className="mr-2" />
                              Requested Analysis &amp; Parameters
                            </h4>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                              {report.requested_sheets?.length > 0 && (
                                <div>
                                  <p className="text-xs font-semibold text-gray-500 uppercase mb-2">Requested Sheets</p>
                                  <div className="flex flex-wrap gap-2">
                                    {report.requested_sheets.map((sheet, idx) => (
                                      <span
                                        key={`${report._id}-sheet-${idx}`}
                                        className="px-2 py-1 bg-purple-50 text-purple-700 text-xs rounded border border-purple-100"
                                      >
                                        {sheet}
                                      </span>
                                    ))}
                                  </div>
                                </div>
                              )}
                              {report.analysis_options?.extra_data && (
                                <div>
                                  <p className="text-xs font-semibold text-gray-500 uppercase mb-2">Analysis Parameters</p>
                                  <div className="space-y-2 text-sm">
                                    {report.analysis_options.extra_data.sensitivity && (
                                      <div className="p-2 bg-orange-50 rounded border border-orange-100">
                                        <p className="text-xs font-medium text-orange-800">Sensitivity Analysis</p>
                                        <p className="text-gray-700">
                                          Selling Price Decrease:{' '}
                                          <span className="font-bold">
                                            {report.analysis_options.extra_data.sensitivity.sellingPriceDecrease}%
                                          </span>
                                        </p>
                                      </div>
                                    )}
                                    {report.analysis_options.extra_data.bep && (
                                      <div className="p-2 bg-green-50 rounded border border-green-100">
                                        <p className="text-xs font-medium text-green-800">BEP Analysis</p>
                                        <div className="grid grid-cols-2 gap-x-4 gap-y-1 mt-1">
                                          <p className="text-xs text-gray-500">
                                            Unit:{' '}
                                            <span className="text-gray-800 font-medium">
                                              {report.analysis_options.extra_data.bep.productManufactured}
                                            </span>
                                          </p>
                                          <p className="text-xs text-gray-500">
                                            Price:{' '}
                                            <span className="text-gray-800 font-medium">
                                              ₹{report.analysis_options.extra_data.bep.sellingPricePerUnit}
                                            </span>
                                          </p>
                                          <p className="text-xs text-gray-500">
                                            Growth:{' '}
                                            <span className="text-gray-800 font-medium">
                                              {report.analysis_options.extra_data.bep.sellingPriceGrowth}%
                                            </span>
                                          </p>
                                          <p className="text-xs text-gray-500">
                                            Capacity:{' '}
                                            <span className="text-gray-800 font-medium">
                                              {report.analysis_options.extra_data.bep.plantCapacity}
                                            </span>
                                          </p>
                                        </div>
                                      </div>
                                    )}
                                  </div>
                                </div>
                              )}
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </>
          )}
        </div>

        {/* Pagination */}
        {pagination.total_pages > 1 && (
          <div className="flex justify-center items-center gap-2 mt-6">
            <button
              type="button"
              onClick={() => fetchReports(pagination.current_page - 1)}
              disabled={pagination.current_page === 1}
              className="px-4 py-2 border border-gray-300 rounded-lg disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50"
            >
              Previous
            </button>
            <span className="text-gray-600">
              Page {pagination.current_page} of {pagination.total_pages}
            </span>
            <button
              type="button"
              onClick={() => fetchReports(pagination.current_page + 1)}
              disabled={pagination.current_page === pagination.total_pages}
              className="px-4 py-2 border border-gray-300 rounded-lg disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50"
            >
              Next
            </button>
          </div>
        )}
      </div>

      {/* PDF Viewer Modal */}
      {showPdfViewer && selectedReport && (
        <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-5xl h-[90vh] flex flex-col">
            <div className="p-4 border-b border-gray-200 flex justify-between items-center">
              <h2 className="text-lg font-semibold text-gray-800">
                {selectedReport.title} - PDF Preview
              </h2>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleDownloadPdf}
                  className="flex items-center px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700"
                >
                  <Download size={16} className="mr-2" />
                  Download
                </button>
                <button
                  type="button"
                  onClick={closePdfViewer}
                  className="p-2 text-gray-500 hover:text-gray-700"
                  title="Close"
                >
                  <X size={24} />
                </button>
              </div>
            </div>
            <div className="flex-1 overflow-hidden bg-gray-100 flex items-center justify-center">
              {loadingPdf ? (
                <div className="flex flex-col items-center gap-3">
                  <Loader2 className="animate-spin text-purple-600" size={48} />
                  <p className="text-gray-600">Loading PDF...</p>
                </div>
              ) : pdfBlobUrl ? (
                <iframe src={pdfBlobUrl} className="w-full h-full" title="PDF Preview" />
              ) : (
                <p className="text-red-600">Failed to load PDF</p>
              )}
            </div>
          </div>
        </div>
      )}
    </AdminLayout>
  );
};

export default CompanyAdminReportsPage;
