import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import ClientLayout from '../components/layouts/ClientLayout';
import useAuth from '../hooks/useAuth';
import { FileStack, User, ClipboardList, ArrowRight } from 'lucide-react';

const CustomerDashboardPage = () => {
  const navigate = useNavigate();
  const { user, getProfile } = useAuth();

  useEffect(() => {
    getProfile().catch(() => {});
  }, [getProfile]);

  return (
    <ClientLayout>
      <div className="py-6 space-y-8 font-['Inter']">
        <div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-purple-800 to-indigo-900 text-white p-8 sm:p-12 shadow-xl">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,_var(--tw-gradient-stops))] from-white/10 via-transparent to-transparent"></div>
          <div className="relative z-10 max-w-2xl">
            <h1 className="text-3xl sm:text-4xl font-bold font-['Manrope'] mb-3">
              Welcome back, {user?.name || 'Customer'}!
            </h1>
            <p className="text-purple-100 text-lg mb-6">
              Track your report requests, view generated documents, and manage your account settings from one clean interface.
            </p>
            <div className="flex flex-wrap gap-4">
              <button
                onClick={() => navigate('/customer/reports')}
                className="inline-flex items-center gap-2 px-6 py-3 bg-white text-purple-900 rounded-full font-semibold hover:bg-purple-50 transition-all shadow-md hover:shadow-lg"
              >
                View My Reports
                <ArrowRight size={18} />
              </button>
              <button
                onClick={() => navigate('/customer/department-requests')}
                className="inline-flex items-center gap-2 px-6 py-3 bg-white/10 border border-white/30 text-white rounded-full font-semibold hover:bg-white/20 transition-all"
              >
                My Requests
                <ArrowRight size={18} />
              </button>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div
            onClick={() => navigate('/customer/department-requests')}
            className="group cursor-pointer bg-white rounded-2xl border border-gray-200 p-8 shadow-sm hover:shadow-md transition-all flex items-start gap-6 hover:border-purple-200"
          >
            <div className="w-14 h-14 rounded-2xl bg-purple-50 text-purple-700 flex items-center justify-center flex-shrink-0 group-hover:bg-purple-100 transition-colors">
              <ClipboardList size={28} />
            </div>
            <div>
              <h3 className="text-xl font-bold text-gray-900 mb-2 font-['Manrope']">My Requests</h3>
              <p className="text-gray-600 text-sm leading-relaxed mb-4">
                Track department form submissions and processing stage until your report is approved.
              </p>
              <span className="text-sm font-semibold text-purple-700 inline-flex items-center gap-1 group-hover:text-purple-800">
                View Requests <ArrowRight size={14} className="group-hover:translate-x-0.5 transition-transform" />
              </span>
            </div>
          </div>

          <div
            onClick={() => navigate('/customer/reports')}
            className="group cursor-pointer bg-white rounded-2xl border border-gray-200 p-8 shadow-sm hover:shadow-md transition-all flex items-start gap-6 hover:border-purple-200"
          >
            <div className="w-14 h-14 rounded-2xl bg-purple-50 text-purple-700 flex items-center justify-center flex-shrink-0 group-hover:bg-purple-100 transition-colors">
              <FileStack size={28} />
            </div>
            <div>
              <h3 className="text-xl font-bold text-gray-900 mb-2 font-['Manrope']">My Reports</h3>
              <p className="text-gray-600 text-sm leading-relaxed mb-4">
                Access all your final and approved reports generated by the Customer Service team.
              </p>
              <span className="text-sm font-semibold text-purple-700 inline-flex items-center gap-1 group-hover:text-purple-800">
                Go to Reports <ArrowRight size={14} className="group-hover:translate-x-0.5 transition-transform" />
              </span>
            </div>
          </div>

          <div
            onClick={() => navigate('/customer/profile')}
            className="group cursor-pointer bg-white rounded-2xl border border-gray-200 p-8 shadow-sm hover:shadow-md transition-all flex items-start gap-6 hover:border-purple-200"
          >
            <div className="w-14 h-14 rounded-2xl bg-purple-50 text-purple-700 flex items-center justify-center flex-shrink-0 group-hover:bg-purple-100 transition-colors">
              <User size={28} />
            </div>
            <div>
              <h3 className="text-xl font-bold text-gray-900 mb-2 font-['Manrope']">Account Profile</h3>
              <p className="text-gray-600 text-sm leading-relaxed mb-4">
                Manage your profile configuration and contact details.
              </p>
              <span className="text-sm font-semibold text-purple-700 inline-flex items-center gap-1 group-hover:text-purple-800">
                Manage Profile <ArrowRight size={14} className="group-hover:translate-x-0.5 transition-transform" />
              </span>
            </div>
          </div>
        </div>
      </div>
    </ClientLayout>
  );
};

export default CustomerDashboardPage;
