/**
 * Sample fill data for BOI HOME LOAN DDA (aligned with sample report).
 */

const TINY_PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';

export function makeTestEvidenceFile(name = 'site-photo.png') {
  const binary = atob(TINY_PNG_BASE64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return new File([bytes], name, { type: 'image/png' });
}

function emptyApplicant() {
  return {
    borrower_name: '',
    father_spouse: '',
    gender: '',
    resident_status: '',
    pan: '',
    aadhaar: '',
    dob: '',
    qualification: '',
    marital_status: '',
    employment_type: '',
    permanent_address: '',
    telephone: '',
    trade_licence: '',
    type_of_loan: 'Home Loan / Loan Against Property / Mortgage-Backed Loan',
    summary_personal: '',
    summary_residence: '',
    summary_telephone: '',
    summary_payslips: '',
    summary_form16: '',
    summary_employer: '',
    summary_office_place: '',
    summary_bank: '',
    summary_other: '',
    res_address_tallied: '',
    res_landmark: '',
    res_stay_confirmed: '',
    res_nameplate_seen: '',
    res_nameplate_tally: '',
    res_nature: '',
    res_type: '',
    res_person_contacted: '',
    res_relation: '',
    res_city: '',
    res_pincode: '',
    res_phone: '',
    res_mobile: '',
    res_locality_type: '',
    res_locality: '',
    res_present_address: '',
    res_family_members: '',
    res_earning_members: '',
    res_years: '',
    res_accessibility: '',
    res_vehicles: '',
    emp_narrative: '',
    emp_name: '',
    emp_address: '',
    emp_confirmed_by: '',
    emp_landmark: '',
    emp_ownership: '',
    emp_nameboard: '',
    emp_nameboard_comments: '',
    emp_proofs: '',
    emp_designation: '',
    emp_year_est: '',
    emp_firm_type: '',
    emp_nature: '',
    emp_website: '',
    emp_since: '',
    emp_change_likelihood: '',
    emp_line: '',
    emp_phone: '',
    emp_terms: '',
    emp_grade: '',
    emp_supervisor: '',
    emp_visiting_card: '',
    pan_number: '',
    pan_name_match: '',
    pan_gender_match: '',
    pan_tenth_alpha: '',
    pan_digits_numeric: '',
    pan_fourth_digit: '',
    pan_fifth_match: '',
    pan_it_verified: '',
    pan_final_status: '',
    pan_remarks: '',
    pan_verifier: '',
    pan_supervisor: '',
    pan_negative: '',
    sal_firm: '',
    sal_designation: '',
    sal_years: '',
    sal_confirmed: '',
    sal_gross: '',
    sal_total_income: '',
    sal_head_verified: '',
    sal_tax_verified: '',
    sal_form16_correct: '',
    sal_no_remarks: '',
    doc_seal: '',
    doc_signature: '',
    doc_date_amount: '',
    doc_office_address: '',
  };
}

export function getBoiHomeLoanEmptyState(applicantCount = 1) {
  const count = Math.min(4, Math.max(1, Number(applicantCount) || 1));
  return {
    num_applicants: count,
    report_date: '',
    bank_name: 'Bank of India',
    branch_name: '',
    loan_type: 'Home Loan / Loan Against Property / Mortgage-Backed Loan',
    bank_reference_no: '',
    dda_reference_no: '',
    date_receipt: '',
    date_submission: '',
    proposal_branch: '',
    loan_amount: '',
    overall_visit_datetime: '',
    overall_status: '',
    overall_opinion: '',
    res_narrative_visit: '',
    res_narrative_details: '',
    res_narrative_family: '',
    res_narrative_living: '',
    res_narrative_conclusion: '',
    locked_stay: '',
    locked_age: '',
    locked_family: '',
    locked_occupation: '',
    locked_since: '',
    unconfirmed_reason: '',
    unconfirmed_untraceable: '',
    unconfirmed_mismatch: '',
    living_standard: '',
    living_colour: '',
    living_interior: '',
    living_assets: '',
    living_storeys: '',
    living_watchman: '',
    living_lift: '',
    living_society: '',
    living_cars: '',
    living_appearance: '',
    living_parking: '',
    living_entry: '',
    living_size: '',
    neighbour_remarks: '',
    res_signoff_datetime: '',
    res_signoff_verifier: '',
    res_signoff_supervisor: '',
    res_signoff_negative: '',
    res_conclusion_status: '',
    premises_type: '',
    premises_locality: '',
    premises_building: '',
    premises_hours: '',
    premises_employees: '',
    premises_branches: '',
    premises_separate_area: '',
    premises_status: '',
    emp_signoff_verifier: '',
    emp_signoff_supervisor: '',
    emp_signoff_negative: '',
    prop_identifier: '',
    prop_visit_date: '',
    prop_title_verified: '',
    prop_others: '',
    prop_valuation: '',
    builder_since: '',
    builder_projects: '',
    builder_sold: '',
    builder_constructed: '',
    builder_enquiry1: '',
    builder_enquiry2: '',
    builder_quality: '',
    builder_nature: '',
    builder_approved: '',
    itr_latest: '',
    itr_preceding: '',
    itr_second: '',
    itr_verified: '',
    bank_applicant_name: '',
    bank_account_no: '',
    bank_name_branch: '',
    bank_observations: '',
    cert_place: '',
    cert_date: '',
    cert_udin: '',
    cert_auditor: '',
    cert_name: '',
    auditor_name: '',
    photo_captions: [],
    photo_names: [],
    applicants: Array.from({ length: count }, () => emptyApplicant()),
  };
}

export function getBoiHomeLoanTestData(user = {}, applicantCount = 1) {
  const count = Math.min(4, Math.max(1, Number(applicantCount) || 1));
  const base = getBoiHomeLoanEmptyState(count);
  const app1 = {
    ...emptyApplicant(),
    borrower_name: 'Addanki Rama Krishna',
    father_spouse: 'S/o Late Addanki Venkata Rao',
    gender: 'Male',
    resident_status: 'Resident',
    pan: 'AQMPR7262D',
    aadhaar: '1234 5678 9012',
    dob: '15/06/1978',
    qualification: 'M.Sc., B.Ed.',
    marital_status: 'Married',
    employment_type: 'Salaried / Contract Subject Expert (TGSWREIS)',
    permanent_address:
      '4/11/ER, Rama Krishna Puram, Ramakrishna Puram, Hyderabad, Telangana 501505',
    telephone: '9876543210',
    trade_licence: 'Not Applicable',
    type_of_loan: 'HOME LOAN',
    summary_personal: 'Positive',
    summary_residence: 'Positive',
    summary_telephone: 'Positive',
    summary_payslips: 'Positive',
    summary_form16: 'Positive',
    summary_employer: 'Positive',
    summary_office_place: 'Positive',
    summary_bank: 'Positive',
    summary_other: 'Positive',
    res_address_tallied: 'Yes',
    res_landmark: 'Near local temple / main road',
    res_stay_confirmed: 'Yes - Staying since ~2015',
    res_nameplate_seen: 'Yes',
    res_nameplate_tally: 'Yes',
    res_nature: 'Rental / Family Owned',
    res_type: 'Independent House',
    res_person_contacted: 'Smt. A. Bhavani (Wife)',
    res_relation: 'Spouse',
    res_city: 'Hyderabad',
    res_pincode: '501505',
    res_phone: 'N/A',
    res_mobile: '9876543210',
    res_locality_type: 'Residential',
    res_locality: 'Rama Krishna Puram',
    res_present_address: '4/11/ER, Rama Krishna Puram, Hyderabad, Telangana 501505',
    res_family_members: '4',
    res_earning_members: '1',
    res_years: 'Approx. 10 years',
    res_accessibility: 'Easy to locate',
    res_vehicles: 'Two-wheelers observed',
    emp_narrative:
      'Visited employment premises on 03/08/2026; met supervisory official; employment confirmed and found satisfactory.',
    emp_name: 'TGSWR School & Jr. College (B), Uppal - TGSWREIS',
    emp_address: 'Uppal / Edulabad campus, Hyderabad, Telangana',
    emp_confirmed_by: 'Office records / Name board',
    emp_landmark: 'School / College campus',
    emp_ownership: 'Institutional / Government campus',
    emp_nameboard: 'Yes',
    emp_nameboard_comments: '',
    emp_proofs: 'ID Card / Letter Head',
    emp_designation: 'Subject Expert (Mathematics)',
    emp_year_est: 'N/A',
    emp_firm_type: 'Others (Govt. Education Society)',
    emp_nature: 'Servicing / Education',
    emp_website: 'N/A',
    emp_since: '24 Years (2 Years in present COE)',
    emp_change_likelihood: 'No adverse information',
    emp_line: 'N/A',
    emp_phone: '040-XXXXXXX',
    emp_terms: 'Full-time / Contract',
    emp_grade: 'Subordinate / Teaching Staff (Subject Expert)',
    emp_supervisor: 'Sri Francis Reddy, Superior Official - 9440393918',
    emp_visiting_card: 'No',
    pan_number: 'AQMPR7262D',
    pan_name_match: 'Yes',
    pan_gender_match: 'Yes',
    pan_tenth_alpha: 'Yes (D)',
    pan_digits_numeric: 'Yes (7262)',
    pan_fourth_digit: 'Yes (P - Individual)',
    pan_fifth_match: 'Yes (R - Rama Krishna)',
    pan_it_verified: 'Yes',
    pan_final_status: 'Confirmed',
    pan_remarks: 'PAN details tally with Aadhaar and Income Tax records',
    pan_verifier: 'Ram Prasad - Confirmed',
    pan_supervisor: 'Shaik Fareed Baba - Verified and concurred',
    pan_negative: 'Not Applicable',
    sal_firm: 'TGSWR School & Jr. College (B), Uppal - TGSWREIS (Education Department)',
    sal_designation: 'Subject Expert (Mathematics)',
    sal_years: '24 Years (2 Years in present COE)',
    sal_confirmed: 'Yes',
    sal_gross: 'Approx. Rs. 1,10,000 per month; Annual gross receipts Rs. 9,43,725',
    sal_total_income: 'Total Income Rs. 10,81,155 as per ITR for AY 2026-27',
    sal_head_verified: 'Not Applicable - Income offered as Business/Professional Income u/s 44AD',
    sal_tax_verified: 'Yes',
    sal_form16_correct: 'Not Applicable (No Form-16; TDS u/s 194JB)',
    sal_no_remarks: 'Not Applicable',
    doc_seal: 'Yes',
    doc_signature: 'Yes',
    doc_date_amount: 'Tallies with TDS / Form 26AS figures',
    doc_office_address: 'Yes',
  };

  const coApplicantNames = ['Addanki Bhavani', 'Addanki Venkata Rao', 'Addanki Sujatha'];
  const applicants = [app1];
  for (let i = 1; i < count; i += 1) {
    applicants.push({
      ...app1,
      borrower_name: coApplicantNames[i - 1] || `Co-Applicant ${i + 1}`,
      pan_number: '',
      pan: '',
      summary_personal: 'Positive',
    });
  }

  return {
    ...base,
    num_applicants: count,
    report_date: '03/08/2026',
    bank_name: 'Bank of India',
    branch_name: 'Adikmet Branch, Hyderabad',
    loan_type: 'HOME LOAN',
    bank_reference_no: 'BOI/ADK/2026/047',
    dda_reference_no: 'PN/DDA/HL/2026/047',
    date_receipt: '01/08/2026',
    date_submission: '03/08/2026',
    proposal_branch: 'Bank of India, Adikmet Branch, Hyderabad',
    loan_amount: 'As per bank proposal',
    overall_visit_datetime:
      '03/08/2026 — Residence: 02:37 PM; Employment: forenoon visit',
    overall_status: 'Positive',
    overall_opinion:
      'Physical verification at residence and workplace completed. Particulars tallied with documents. Proposal recommended subject to bank norms.',
    res_narrative_visit:
      'Visited the given residential address on 03.08.2026 at 02:37 PM and met applicant\'s wife Smt. A. Bhavani at the gate.',
    res_narrative_details:
      'Independent house in residential locality; family residing for about 10 years; surroundings average to good.',
    res_narrative_family: 'Four family members; spouse interviewed during visit.',
    res_narrative_living:
      'Building condition good; middle to upper-middle standard of living observed.',
    res_narrative_conclusion: 'Residential address confirmed and found satisfactory.',
    locked_stay: 'Not Applicable - Applicant\'s family member met at residence',
    locked_age: 'Not Applicable',
    locked_family: 'Not Applicable',
    locked_occupation: 'Not Applicable',
    locked_since: 'Not Applicable',
    unconfirmed_reason: 'Not Applicable - Address Confirmed',
    unconfirmed_untraceable: 'Not Applicable',
    unconfirmed_mismatch: 'Not Applicable',
    living_standard: 'Middle / Upper-Middle',
    living_colour: 'Brown / cream exterior',
    living_interior: 'Painted / Furnished',
    living_assets: 'Television / Refrigerator',
    living_storeys: 'G+2 (visual)',
    living_watchman: 'No',
    living_lift: 'No',
    living_society: 'No (Independent house, not a society)',
    living_cars: 'Nil (Two-wheelers observed)',
    living_appearance: 'Good',
    living_parking: 'Yes (Open parking at ground floor)',
    living_entry: 'Yes',
    living_size: 'Approx. 1,200-1,500 sq. ft. (visual estimate)',
    neighbour_remarks:
      'Neighbours in the vicinity confirmed that the applicant\'s family has been residing at the address; no adverse remarks received.',
    res_signoff_datetime: '03.08.2026, 02:37 PM',
    res_signoff_verifier: 'Ram Prasad - Residence confirmed and found satisfactory',
    res_signoff_supervisor: 'Shaik Fareed Baba - Verified and concurred with the field report',
    res_signoff_negative: 'Not Applicable',
    res_conclusion_status: 'Confirmed and Found Satisfactory',
    premises_type: 'Residential (School/College Campus)',
    premises_locality: 'Average (Semi-Urban - Edulabad)',
    premises_building: 'School / College Complex',
    premises_hours: '9:00 AM to 5:00 PM (approx.)',
    premises_employees: '10 Subject Experts working at this COF (as per TGSWREIS records)',
    premises_branches: 'Multiple COFs under TGSWREIS across Telangana',
    premises_separate_area: 'Not Applicable',
    premises_status:
      'Reception Area: Yes; Security Guard: Yes; Cabin: No; AC: No; Xerox: No; Fax: No; Computer: Yes',
    emp_signoff_verifier: 'Ram Prasad - Employment confirmed and found satisfactory',
    emp_signoff_supervisor: 'Shaik Fareed Baba - Verified and concurred',
    emp_signoff_negative: 'Not Applicable',
    prop_identifier: 'As per bank valuation / title documents on record',
    prop_visit_date: '03/08/2026',
    prop_title_verified: 'Yes',
    prop_others: 'Site photographs annexed',
    prop_valuation: 'As per valuation report submitted to bank',
    builder_since: 'Not Applicable',
    builder_projects: 'Not Applicable',
    builder_sold: 'Not Applicable',
    builder_constructed: 'Not Applicable',
    builder_enquiry1: 'Not Applicable',
    builder_enquiry2: 'Not Applicable',
    builder_quality: 'Not Applicable',
    builder_nature: 'Non-Agricultural / Residential',
    builder_approved: 'Not Applicable',
    itr_latest: 'AY 2026-27 — Total Income Rs. 10,81,155 — Filed — Ack. as per portal',
    itr_preceding: 'AY 2025-26 — As per ITR acknowledgement',
    itr_second: 'AY 2024-25 — As per ITR acknowledgement',
    itr_verified: 'Yes',
    bank_applicant_name: 'Addanki Rama Krishna',
    bank_account_no: 'XXXXXXXXXXXX',
    bank_name_branch: 'Bank of India, Adikmet Branch (IFSC as per passbook)',
    bank_observations:
      'Account shows salary/professional credits and routine debits; no adverse patterns observed in the period reviewed.',
    cert_place: 'Hyderabad',
    cert_date: '03/08/2026',
    cert_udin: 'XXXXXXXXXXXX',
    cert_auditor: 'PARVEZ AND NARAYANA, CHARTERED ACCOUNTANTS',
    cert_name: user?.name || 'PARVEZ MOHAMMED',
    auditor_name: user?.name || 'PARVEZ MOHAMMED',
    photo_captions: [
      'Residence Verification - Exterior view of residence at Rama Krishna Puram, Hyderabad (03.08.2026, 02:37 PM) - Applicant\'s wife Smt. A. Bhavani met at the gate',
    ],
    photo_names: ['Addanki Rama Krishna'],
    applicants,
  };
}

export { emptyApplicant };
