/**
 * Sample fill data for BOI MSME Due Diligence Report (aligned with sample PDF).
 */

const TINY_PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';

export function makeTestEvidenceFile(name = 'site-photo.png') {
  const binary = atob(TINY_PNG_BASE64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return new File([bytes], name, { type: 'image/png' });
}

export function getBoiMsmeTestData(user = {}) {
  const today = '08-07-2026';
  return {
    report_date: today,
    bank_name: 'Punjab and Sind Bank',
    branch_name: 'Chennai Branch',
    date_of_visit:
      '06-07-2026 (site visit conducted at the registered office-cum-residence premises at D.No. 22-4-300, Nethaji Road, Tirupati)',
    persons_met: 'Y. Eswara Reddy (Partner); Field executive from Parvez and Narayana',
    personnel: [
      { name: 'Y. Eswara Reddy', designation: 'Partner', years_of_service: 'Since 12-09-2020' },
      { name: 'Y. Sujatha', designation: 'Partner', years_of_service: 'Since 12-09-2020' },
    ],
    borrower_name_address:
      'M/s. Sri Sai Teja Enterprises\nD.No. 22-4-300, Nethaji Road, Tirupati, Andhra Pradesh - 517501',
    telephone: 'Residence: 9876543210 / Office: 9876543211',
    electricity: 'Active domestic-cum-commercial connection in the name of Y. Sujatha; bills paid regularly',
    other_sites: 'Nil – operations from registered office-cum-residence only',
    trade_license:
      'GSTIN: 37XXXXX1234A1Z5 (Active)\nUdyam Registration: UDYAM-AP-XX-0001234\nVerified against online portal during visit',
    constitution: 'Partnership Firm',
    partners: [
      {
        name: 'Y. Eswara Reddy S/o Y. Venkata Reddy',
        pan: 'ABCDE1234F',
        relationship: 'Partner',
      },
      {
        name: 'Y. Sujatha W/o Y. Eswara Reddy',
        pan: 'FGHIJ5678K',
        relationship: 'Partner',
      },
    ],
    residential_address: 'D.No. 22-4-300, Nethaji Road, Tirupati - 517501',
    family_members: 'Spouse and two dependents residing at the same premises',
    landmark: 'Near Nethaji Circle / local temple',
    partner_business_details: 'Partners actively manage wholesale/retail trading of general merchandise',
    email_ids: 'srisaitaja@example.com',
    office_contacts: '0877-XXXXXXX',
    year_of_establishment: '2020',
    registrations_affiliations: 'GST, Udyam, Trade licence – no change in promoters since constitution',
    awards: 'Nil',
    registered_office_change: 'No change',
    legal_proceedings: 'Nil as informed / no adverse information from public domain search',
    disputes: 'Nil',
    business_profile: 'Trading concern – wholesale and retail of general merchandise',
    products: 'FMCG / general merchandise',
    installed_capacity: 'Not applicable (trading concern)',
    asset_land_buildings: false,
    asset_land_buildings_note: '',
    asset_plant_machinery: false,
    asset_plant_machinery_note: 'Not applicable (trading concern)',
    asset_furniture: false,
    asset_furniture_note: 'Not separately furnished',
    asset_other: true,
    asset_other_note: 'Jewellery Rs.6.00 lakh; Cash in hand Rs.3.00 lakh (personal, per Statement of Assets & Liabilities)',
    no_of_employees: 'Not furnished; to be ascertained on physical visit',
    premises_owned: true,
    premises_owned_note:
      'Registered office-cum-residence at D.No. 22-4-300, Nethaji Road, Tirupati – owned by partner Y. Sujatha',
    premises_leased: false,
    premises_leased_note: '',
    banking_relationships: [
      {
        bank: 'Punjab & Sind Bank (George Town Branch)',
        facility: 'Overdraft/Dropline OD (ODP)',
        sanctioned: 'Rs. 80.00 lakh (existing)',
        outstanding: 'Rs. 82,06,386 (as on 31.03.2025 per audited B/S)',
        emi: 'N/A',
      },
    ],
    personal_assets: [
      {
        name: 'Y. Eswara Reddy',
        description: 'Vacant plot, Chinnagottigallu Mandal, Tirupati',
        amount: '8.14',
        offered_as_security: 'No',
      },
      {
        name: 'Y. Sujatha',
        description: 'Residential property D.No. 22-4-300, Nethaji Road, Tirupati',
        amount: '230.00',
        offered_as_security: 'Yes - Offered as Equitable Mortgage',
      },
    ],
    clients: [
      {
        name_contact: 'Local wholesale buyers / retailers',
        location: 'Tirupati & surrounding',
        relationship_years: '3–5',
        credit_period: '15–30 days',
      },
    ],
    quality_of_debts: 'Generally satisfactory; concentration risk noted on few large buyers',
    suppliers: [
      {
        name_contact: 'Regional distributors',
        location: 'Chennai / Hyderabad',
        relationship_years: '2–4',
        credit_period: '21–45 days',
      },
    ],
    payment_track_record: 'Satisfactory as informed; no major disputes reported',
    associates: [
      { name: 'Nil', nature: '—', bankers: '—' },
    ],
    insurance_assets_covered: 'Stock and premises (to the extent covered under existing policies)',
    insurance_policies: [
      {
        policy_no: 'To be furnished',
        validity: 'Current year',
        sum_assured: 'As per policy',
        risk_covered: 'Fire / burglary (stock)',
      },
    ],
    last_financial_statement: '31/03/2025 (audited)',
    recent_summary_financials: 'Provisional figures up to May 2026 furnished by management',
    advance_taxes: 'Paid as applicable',
    change_in_borrowings: 'Proposed enhancement / restructuring of OD limits under discussion',
    debtors_position: 'Receivables within normal trade cycle; amount >90 days to be monitored',
    creditors_position: 'Trade creditors within agreed credit periods',
    stock_position: 'Stock levels consistent with turnover; physical verification recommended periodically',
    drawing_power: 'As per bank DP statement',
    other_material_development: 'Nil material adverse development reported',
    current_ratio: '1.45',
    debt_equity_ratio: '1.20',
    dscr: '1.35',
    tol_tnw: '2.10',
    other_business_interests: 'Partners primarily engaged in the subject firm; no other material concerns informed',
    bank_credits_debits: 'High credit and debit turnover consistent with trading activity',
    bank_month_credits: 'Month-wise credits show healthy business throughput (block credits ignored)',
    cheque_bounces: 'Nil / not observed in the period reviewed',
    debt_servicing_evidence: 'Existing OD interest serviced; no reported defaults',
    line_utilisation: 'Utilisation near sanctioned; no clear evidence of perennial overdrawing beyond limit',
    statutory_dues: 'GST returns filed; no dues flagged during visit',
    pf_employee: 'Not applicable / limited staff',
    municipal_taxes: 'Property tax receipts verified for mortgaged property',
    utility_payments: 'Electricity bills paid; last payment within recent billing cycle',
    employees_observed: '2–3 persons at premises during visit',
    activity_level: 'Trading/desk activity observed; invoices and stock records available',
    factory_location: 'Not applicable – trading concern',
    raw_materials: 'N/A',
    manufacturing_process: 'N/A',
    machines: 'N/A',
    pollution_control: 'N/A',
    pcb_permission: 'N/A',
    power: 'Domestic/commercial connection adequate for office use',
    inventory: 'Trading stock stored within premises',
    storage_security: 'Locked premises; residential-cum-office security',
    quality_certification: 'N/A',
    workers: 'Family-run with limited hired help; no unions',
    labour_history: 'No strikes / no child labour observed',
    purchases_sales: [
      { month: 'Apr 2026', purchases: 'Rs. 45 lakh', sales: 'Rs. 52 lakh' },
      { month: 'May 2026', purchases: 'Rs. 48 lakh', sales: 'Rs. 55 lakh' },
    ],
    documents_verified:
      'Partnership deed, GST, Udyam, PAN/Aadhaar of partners, bank statements, audited financials, title documents (property)',
    record_balance_sheets: 'Verified (FY 2023–25)',
    record_pl: 'Verified',
    record_computation: 'Verified',
    record_itr: 'ITR acknowledgements verified',
    record_photo_id: 'Aadhaar / PAN of partners verified',
    roc_summary: 'Partnership firm – ROC company search N/A; partnership deed and registrations reviewed',
    roc_partners: [
      {
        name_designation: 'Y. Eswara Reddy – Partner',
        address: 'Tirupati',
        appointment_date: '12-09-2020',
        cessation_date: '—',
      },
      {
        name_designation: 'Y. Sujatha – Partner',
        address: 'Tirupati',
        appointment_date: '12-09-2020',
        cessation_date: '—',
      },
    ],
    property_identifier: 'Y. Sujatha, D.No. 22-4-300, Nethaji Road, Tirupati',
    property_visit_date: '06-07-2026',
    property_title_verified: 'Yes – original title deeds / tax receipts verified',
    property_others: 'Gate nameplate confirms owner Y. Sujatha',
    property_valuation: 'Approx. Rs. 2.30 Cr as per valuation report on record',
    property_cgtmse: 'As proposed by bank / to be confirmed',
    swot_strengths:
      'Established local trading franchise; owned residential-cum-office collateral; active GST compliance',
    swot_weakness: 'Receivables concentration; family-run with limited formal systems',
    swot_opportunities: 'Limit enhancement to support turnover growth; wider buyer base',
    swot_threat: 'Working-capital stress if receivables elongate; competition from organised retail',
    conclusion_kyc:
      'Partnership firm; partners KYC (PAN/Aadhaar/Udyam/GST) verified; constitution since 12-09-2020',
    conclusion_financial:
      'Turnover growth observed FY23–FY26 (provisional); margins modest; ratios within acceptable band for trading',
    conclusion_banking:
      'Account shows high-value pass-throughs consistent with trade; no cheque bounces noted; existing PSB ODP utilised',
    conclusion_collateral:
      'Residential property offered as EM valued ~Rs. 2.30 Cr; physical visit and title documents verified',
    conclusion_overall:
      'Proposal appears bankable subject to monitoring of receivables concentration and confirmation of insurance/stock DP',
    photo_captions: [
      'Partner Y. Eswara Reddy at office desk (06-07-2026, 1:14 PM)',
      'Front elevation of registered office-cum-residence premises',
      'Gate nameplate confirming owner Y. Sujatha, D.No. 22-4-300',
      'Business signboard with GSTIN',
      'Signboard inside the premises',
      'Office desk with laptop/documents',
      'Partner with field representative (selfie)',
    ],
    auditor_name: user?.name || 'PARVEZ MOHAMMED',
    auditor_date: '09-07-2026',
    auditor_display_name: user?.name || 'PARVEZ MOHAMMED',
    attestation_text:
      'This report has been prepared based on unit visit, the financial records and in the said report seem true and correct to the best of our knowledge and belief. All photographs are geo-tagged and corroborate the registered office address.',
  };
}

export function getBoiMsmeEmptyState() {
  return {
    report_date: '',
    bank_name: '',
    branch_name: '',
    date_of_visit: '',
    persons_met: '',
    personnel: [{ name: '', designation: '', years_of_service: '' }],
    borrower_name_address: '',
    telephone: '',
    electricity: '',
    other_sites: '',
    trade_license: '',
    constitution: '',
    partners: [{ name: '', pan: '', relationship: '' }],
    residential_address: '',
    family_members: '',
    landmark: '',
    partner_business_details: '',
    email_ids: '',
    office_contacts: '',
    year_of_establishment: '',
    registrations_affiliations: '',
    awards: '',
    registered_office_change: '',
    legal_proceedings: '',
    disputes: '',
    business_profile: '',
    products: '',
    installed_capacity: '',
    asset_land_buildings: false,
    asset_land_buildings_note: '',
    asset_plant_machinery: false,
    asset_plant_machinery_note: '',
    asset_furniture: false,
    asset_furniture_note: '',
    asset_other: false,
    asset_other_note: '',
    no_of_employees: '',
    premises_owned: false,
    premises_owned_note: '',
    premises_leased: false,
    premises_leased_note: '',
    banking_relationships: [
      { bank: '', facility: '', sanctioned: '', outstanding: '', emi: '' },
    ],
    personal_assets: [
      { name: '', description: '', amount: '', offered_as_security: '' },
    ],
    clients: [
      { name_contact: '', location: '', relationship_years: '', credit_period: '' },
    ],
    quality_of_debts: '',
    suppliers: [
      { name_contact: '', location: '', relationship_years: '', credit_period: '' },
    ],
    payment_track_record: '',
    associates: [{ name: '', nature: '', bankers: '' }],
    insurance_assets_covered: '',
    insurance_policies: [
      { policy_no: '', validity: '', sum_assured: '', risk_covered: '' },
    ],
    last_financial_statement: '',
    recent_summary_financials: '',
    advance_taxes: '',
    change_in_borrowings: '',
    debtors_position: '',
    creditors_position: '',
    stock_position: '',
    drawing_power: '',
    other_material_development: '',
    current_ratio: '',
    debt_equity_ratio: '',
    dscr: '',
    tol_tnw: '',
    other_business_interests: '',
    bank_credits_debits: '',
    bank_month_credits: '',
    cheque_bounces: '',
    debt_servicing_evidence: '',
    line_utilisation: '',
    statutory_dues: '',
    pf_employee: '',
    municipal_taxes: '',
    utility_payments: '',
    employees_observed: '',
    activity_level: '',
    factory_location: '',
    raw_materials: '',
    manufacturing_process: '',
    machines: '',
    pollution_control: '',
    pcb_permission: '',
    power: '',
    inventory: '',
    storage_security: '',
    quality_certification: '',
    workers: '',
    labour_history: '',
    purchases_sales: [{ month: '', purchases: '', sales: '' }],
    documents_verified: '',
    record_balance_sheets: '',
    record_pl: '',
    record_computation: '',
    record_itr: '',
    record_photo_id: '',
    roc_summary: '',
    roc_partners: [
      { name_designation: '', address: '', appointment_date: '', cessation_date: '' },
    ],
    property_identifier: '',
    property_visit_date: '',
    property_title_verified: '',
    property_others: '',
    property_valuation: '',
    property_cgtmse: '',
    swot_strengths: '',
    swot_weakness: '',
    swot_opportunities: '',
    swot_threat: '',
    conclusion_kyc: '',
    conclusion_financial: '',
    conclusion_banking: '',
    conclusion_collateral: '',
    conclusion_overall: '',
    photo_captions: [],
    auditor_name: '',
    auditor_date: '',
    auditor_display_name: '',
    attestation_text: '',
  };
}
