/**
 * Admin Lead Register Page
 * Register a new lead and link them to services
 */

import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { createLead, clearLeadError } from '@/store/slices/leadSlice';
import { fetchAllServices } from '@/store/slices/adminServiceSlice';
import {
  ArrowLeft,
  UserPlus,
  Eye,
  EyeOff,
  Copy,
  CheckCircle,
  AlertCircle,
} from 'lucide-react';
import toast from 'react-hot-toast';
import { AdminLayout } from '@/components/layouts';

const AdminLeadRegisterPage = () => {
  const navigate = useNavigate();
  const dispatch = useDispatch();
  const { loading, error } = useSelector((state) => state.lead);
  const { services } = useSelector((state) => state.adminService);

  const [form, setForm] = useState({ name: '', email: '' });
  const [selectedServices, setSelectedServices] = useState([]);
  const [customKeywords, setCustomKeywords] = useState('');
  const [generatedPassword, setGeneratedPassword] = useState(null);
  const [passwordVisible, setPasswordVisible] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    dispatch(fetchAllServices());
    dispatch(clearLeadError());
  }, [dispatch]);

  const handleServiceToggle = (serviceId) => {
    setSelectedServices((prev) =>
      prev.includes(serviceId) ? prev.filter((id) => id !== serviceId) : [...prev, serviceId]
    );
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!form.name.trim() || !form.email.trim()) {
      toast.error('Name and email are required');
      return;
    }

    const keywords = customKeywords
      .split(',')
      .map((k) => k.trim())
      .filter(Boolean);

    try {
      const result = await dispatch(
        createLead({
          name: form.name.trim(),
          email: form.email.trim(),
          services: selectedServices,
          customKeywords: keywords,
        })
      ).unwrap();

      setGeneratedPassword(result.autoGeneratedPassword || null);
      toast.success('Lead registered successfully!');
    } catch (err) {
      toast.error(err || 'Failed to register lead');
    }
  };

  const handleCopy = () => {
    if (!generatedPassword) return;
    navigator.clipboard.writeText(generatedPassword);
    setCopied(true);
    toast.success('Password copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  // Show success screen after registration
  if (generatedPassword) {
    return (
      <AdminLayout>
        <div className="max-w-lg mx-auto mt-16">
          <div className="bg-white rounded-2xl border shadow-sm p-8 text-center space-y-6">
            <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto">
              <CheckCircle className="h-8 w-8 text-green-600" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-gray-900">Lead Registered!</h2>
              <p className="text-gray-500 mt-1">
                Share these credentials with the lead so they can log in.
              </p>
            </div>

            <div className="bg-gray-50 rounded-xl p-5 text-left space-y-3">
              <div>
                <p className="text-xs text-gray-500 font-medium uppercase tracking-wide">Login URL</p>
                <p className="font-medium text-[#7e22ce] mt-0.5">
                  {window.location.origin}/auth
                </p>
              </div>
              <div>
                <p className="text-xs text-gray-500 font-medium uppercase tracking-wide">Email</p>
                <p className="font-medium mt-0.5">{form.email}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 font-medium uppercase tracking-wide">
                  Auto-generated Password
                </p>
                <div className="flex items-center gap-2 mt-0.5">
                  <span className="font-mono text-lg font-semibold tracking-widest">
                    {passwordVisible ? generatedPassword : '•'.repeat(generatedPassword.length)}
                  </span>
                  <button
                    onClick={() => setPasswordVisible(!passwordVisible)}
                    className="p-1 text-gray-400 hover:text-gray-700"
                  >
                    {passwordVisible ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                  </button>
                  <button
                    onClick={handleCopy}
                    className="p-1 text-gray-400 hover:text-gray-700"
                  >
                    {copied ? (
                      <CheckCircle className="h-4 w-4 text-green-600" />
                    ) : (
                      <Copy className="h-4 w-4" />
                    )}
                  </button>
                </div>
              </div>
            </div>

            <p className="text-xs text-amber-600 bg-amber-50 rounded-lg px-4 py-2">
              The lead will be prompted to change their password on first login.
            </p>

            <div className="flex gap-3">
              <button
                onClick={() => {
                  setGeneratedPassword(null);
                  setForm({ name: '', email: '' });
                  setSelectedServices([]);
                  setCustomKeywords('');
                }}
                className="flex-1 px-4 py-2 border rounded-lg hover:bg-gray-50 font-medium"
              >
                Register Another
              </button>
              <button
                onClick={() => navigate('/admin/leads')}
                className="flex-1 px-4 py-2 bg-[#7e22ce] text-white rounded-lg hover:bg-[#6b21a8] font-medium"
              >
                View All Leads
              </button>
            </div>
          </div>
        </div>
      </AdminLayout>
    );
  }

  return (
    <AdminLayout>
      <div className="max-w-2xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate('/admin/leads')}
            className="p-2 rounded-lg hover:bg-gray-100 text-gray-600"
          >
            <ArrowLeft className="h-5 w-5" />
          </button>
          <div>
            <h1 className="text-2xl font-bold">Register New Lead</h1>
            <p className="text-muted-foreground text-sm mt-0.5">
              Add a lead and link them to one or more services
            </p>
          </div>
        </div>

        {/* Error */}
        {error && (
          <div className="flex items-center gap-3 p-4 bg-red-50 border border-red-200 rounded-lg">
            <AlertCircle className="h-5 w-5 text-red-600 flex-shrink-0" />
            <p className="text-red-600 text-sm">{error}</p>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Lead Details */}
          <div className="bg-white rounded-xl border p-6 space-y-4">
            <h2 className="font-semibold text-gray-900 flex items-center gap-2">
              <UserPlus className="h-5 w-5 text-[#7e22ce]" />
              Lead Details
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Full Name <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={form.name}
                  onChange={(e) => setForm({ ...form, name: e.target.value })}
                  placeholder="e.g. Rajesh Kumar"
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-[#7e22ce] focus:border-[#7e22ce]"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Email Address <span className="text-red-500">*</span>
                </label>
                <input
                  type="email"
                  value={form.email}
                  onChange={(e) => setForm({ ...form, email: e.target.value })}
                  placeholder="rajesh@example.com"
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-[#7e22ce] focus:border-[#7e22ce]"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Custom Keywords
                <span className="text-xs text-gray-400 ml-2">(comma-separated, optional)</span>
              </label>
              <input
                type="text"
                value={customKeywords}
                onChange={(e) => setCustomKeywords(e.target.value)}
                placeholder="e.g. fintech, startup, banking"
                className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-[#7e22ce] focus:border-[#7e22ce]"
              />
              <p className="text-xs text-gray-400 mt-1">
                Keywords from linked services are added automatically. These are extra keywords for DPR matching.
              </p>
            </div>
          </div>

          {/* Link Services */}
          <div className="bg-white rounded-xl border p-6 space-y-4">
            <div>
              <h2 className="font-semibold text-gray-900">Link to Services</h2>
              <p className="text-sm text-gray-500 mt-0.5">
                This lead will receive email notifications when forms are submitted for the selected services.
              </p>
            </div>

            {services.length === 0 ? (
              <p className="text-sm text-gray-400 py-4 text-center">No services available</p>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-h-64 overflow-y-auto pr-1">
                {services.map((service) => {
                  const isSelected = selectedServices.includes(service._id);
                  return (
                    <button
                      key={service._id}
                      type="button"
                      onClick={() => handleServiceToggle(service._id)}
                      className={`flex items-start gap-3 p-3 rounded-lg border text-left transition-colors ${
                        isSelected
                          ? 'border-[#7e22ce] bg-purple-50'
                          : 'border-gray-200 hover:border-gray-300 hover:bg-gray-50'
                      }`}
                    >
                      <div
                        className={`w-5 h-5 mt-0.5 rounded flex-shrink-0 border-2 flex items-center justify-center transition-colors ${
                          isSelected ? 'bg-[#7e22ce] border-[#7e22ce]' : 'border-gray-300'
                        }`}
                      >
                        {isSelected && (
                          <svg className="w-3 h-3 text-white" fill="currentColor" viewBox="0 0 12 12">
                            <path d="M10.28 2.28L3.989 8.575 1.695 6.28A1 1 0 00.28 7.695l3 3a1 1 0 001.414 0l7-7A1 1 0 0010.28 2.28z" />
                          </svg>
                        )}
                      </div>
                      <div className="min-w-0">
                        <p className="text-sm font-medium text-gray-900 truncate">{service.name}</p>
                        {service.keywords?.length > 0 && (
                          <p className="text-xs text-gray-400 mt-0.5 truncate">
                            {service.keywords.slice(0, 3).join(', ')}
                            {service.keywords.length > 3 && ` +${service.keywords.length - 3} more`}
                          </p>
                        )}
                      </div>
                    </button>
                  );
                })}
              </div>
            )}

            {selectedServices.length > 0 && (
              <p className="text-sm text-[#7e22ce] font-medium">
                {selectedServices.length} service{selectedServices.length !== 1 ? 's' : ''} selected
              </p>
            )}
          </div>

          {/* Submit */}
          <div className="flex gap-3">
            <button
              type="button"
              onClick={() => navigate('/admin/leads')}
              className="flex-1 px-4 py-2.5 border rounded-lg hover:bg-gray-50 font-medium"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="flex-1 px-4 py-2.5 bg-[#7e22ce] text-white rounded-lg hover:bg-[#6b21a8] font-medium disabled:opacity-60 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {loading ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" />
                  Registering...
                </>
              ) : (
                <>
                  <UserPlus className="h-4 w-4" />
                  Register Lead
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </AdminLayout>
  );
};

export default AdminLeadRegisterPage;
