/**
 * Agent Reports Page
 * View reports generated by the agent
 */

import { useEffect, useState, useMemo } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { AgentLayout } from '../../components/layouts';
import { useAuth } from '../../hooks';
import {
  fetchReports,
  selectReports,
  selectReportLoading,
} from '../../store/slices/reportSlice';
import { Button, Loading } from '../../components/common';
import { reportAPI } from '../../api/endpoints';
import { formatDate, formatDateTime, downloadFile } from '../../utils';
import toast from 'react-hot-toast';
import Invoice from '../../components/Invoice';

// PDF generation libraries
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

// Lucide-react icons for modern UI
import {
  FileText, // For logo
  FileStack, // For reports icon
  User, // For user avatar
  Download, // For download button
  FolderOpen, // For empty state
  CheckCircle, // For approved status
  Clock, // For pending status
  XCircle, // For rejected status
  FileX, // For draft status
  Receipt, // For invoice button
  Calendar, // For date filter
  Filter, // For filter icon
  X, // For close/clear
} from 'lucide-react';

const AgentReportsPage = () => {
  const navigate = useNavigate();
  const dispatch = useDispatch();
  const { user, logout } = useAuth();
  const reports = useSelector(selectReports);
  const loading = useSelector(selectReportLoading);

  const [selectedReport, setSelectedReport] = useState(null);
  const [showInvoice, setShowInvoice] = useState(false);
  const [filters, setFilters] = useState({
    status: '',
    dateFrom: '',
    dateTo: '',
    search: ''
  });

  useEffect(() => {
    if (user?.role === 'agent') {
      dispatch(fetchReports());
    }
  }, [dispatch, user]);

  const filteredReports = useMemo(() => {
    return reports.filter(report => {
      const matchesStatus = !filters.status || report.validation_status === filters.status;
      const matchesSearch = !filters.search ||
        report.title?.toLowerCase().includes(filters.search.toLowerCase()) ||
        report.client_name?.toLowerCase().includes(filters.search.toLowerCase());

      const reportDate = new Date(report.createdAt);
      const matchesDateFrom = !filters.dateFrom || reportDate >= new Date(filters.dateFrom);
      const matchesDateTo = !filters.dateTo || reportDate <= new Date(filters.dateTo + 'T23:59:59');

      return matchesStatus && matchesSearch && matchesDateFrom && matchesDateTo;
    });
  }, [reports, filters]);

  const handleDownload = async (report, type) => {
    try {
      const url = report[`${type}_file_url`];
      if (!url) {
        toast.error(`${type.toUpperCase()} file not available`);
        return;
      }

      await downloadFile(url, `${report.title}_${type}.pdf`);
      toast.success(`${type.toUpperCase()} downloaded successfully`);
    } catch (error) {
      console.error('Download error:', error);
      toast.error(`Failed to download ${type.toUpperCase()}`);
    }
  };

  const handleViewInvoice = (report) => {
    setSelectedReport(report);
    setShowInvoice(true);
  };

  const clearFilters = () => {
    setFilters({
      status: '',
      dateFrom: '',
      dateTo: '',
      search: ''
    });
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case 'approved':
        return <CheckCircle className="w-5 h-5 text-green-500" />;
      case 'pending_validation':
        return <Clock className="w-5 h-5 text-yellow-500" />;
      case 'rejected':
        return <XCircle className="w-5 h-5 text-red-500" />;
      case 'draft':
        return <FileX className="w-5 h-5 text-gray-500" />;
      default:
        return <FileText className="w-5 h-5 text-gray-500" />;
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'approved':
        return 'bg-green-100 text-green-800';
      case 'pending_validation':
        return 'bg-yellow-100 text-yellow-800';
      case 'rejected':
        return 'bg-red-100 text-red-800';
      case 'draft':
        return 'bg-gray-100 text-gray-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <Loading />
      </div>
    );
  }

  return (
    <AgentLayout activeTab="reports">
      <div className="space-y-6">
        {/* Header */}
        <div>
          <h1 className="text-2xl font-bold text-gray-800">My Reports</h1>
          <p className="text-gray-500 mt-1">View reports you have generated</p>
        </div>
        {/* Filters */}
        <div className="bg-white rounded-lg shadow-sm p-6 mb-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-medium text-gray-900">Filters</h2>
            <button
              onClick={clearFilters}
              className="flex items-center space-x-2 px-3 py-1 text-sm text-gray-600 hover:text-gray-800"
            >
              <X className="w-4 h-4" />
              <span>Clear</span>
            </button>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Status</label>
              <select
                value={filters.status}
                onChange={(e) => setFilters(prev => ({ ...prev, status: e.target.value }))}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">All Status</option>
                <option value="approved">Approved</option>
                <option value="pending_validation">Pending</option>
                <option value="rejected">Rejected</option>
                <option value="draft">Draft</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">From Date</label>
              <input
                type="date"
                value={filters.dateFrom}
                onChange={(e) => setFilters(prev => ({ ...prev, dateFrom: e.target.value }))}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">To Date</label>
              <input
                type="date"
                value={filters.dateTo}
                onChange={(e) => setFilters(prev => ({ ...prev, dateTo: e.target.value }))}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-gray-700 mb-1">Search</label>
              <input
                type="text"
                placeholder="Search by title or client..."
                value={filters.search}
                onChange={(e) => setFilters(prev => ({ ...prev, search: e.target.value }))}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
          </div>
        </div>

        {/* Reports List */}
        {filteredReports.length === 0 ? (
          <div className="bg-white rounded-lg shadow-sm p-12 text-center">
            <FolderOpen className="w-16 h-16 text-gray-400 mx-auto mb-4" />
            <h3 className="text-lg font-medium text-gray-900 mb-2">No reports found</h3>
            <p className="text-gray-500">
              {reports.length === 0
                ? "You haven't generated any reports yet."
                : "No reports match your current filters."
              }
            </p>
          </div>
        ) : (
          <div className="bg-white rounded-lg shadow-sm overflow-hidden">
            <div className="px-6 py-4 border-b border-gray-200">
              <h2 className="text-lg font-medium text-gray-900">
                Reports ({filteredReports.length})
              </h2>
            </div>
            <div className="divide-y divide-gray-200">
              {filteredReports.map((report) => (
                <div key={report._id} className="p-6 hover:bg-gray-50">
                  <div className="flex items-center justify-between">
                    <div className="flex-1">
                      <div className="flex items-center space-x-3">
                        <div className="flex-shrink-0">
                          {getStatusIcon(report.validation_status)}
                        </div>
                        <div>
                          <h3 className="text-sm font-medium text-gray-900">
                            {report.title || 'Untitled Report'}
                          </h3>
                          <p className="text-sm text-gray-500">
                            Client: {report.client_name || 'N/A'}
                          </p>
                          <p className="text-xs text-gray-400">
                            Created: {formatDateTime(report.createdAt)}
                          </p>
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center space-x-4">
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(report.validation_status)}`}>
                        {report.validation_status?.replace('_', ' ').toUpperCase()}
                      </span>
                      <div className="flex space-x-2">
                        {report.pdf_file_url && (
                          <button
                            onClick={() => handleDownload(report, 'pdf')}
                            className="px-3 py-1 text-sm text-blue-600 hover:text-blue-800 hover:bg-blue-50 rounded-md transition-colors"
                          >
                            PDF
                          </button>
                        )}
                        {report.json_file_url && (
                          <button
                            onClick={() => handleDownload(report, 'json')}
                            className="px-3 py-1 text-sm text-purple-600 hover:text-purple-800 hover:bg-purple-50 rounded-md transition-colors"
                          >
                            JSON
                          </button>
                        )}
                        <button
                          onClick={() => handleViewInvoice(report)}
                          className="px-3 py-1 text-sm text-gray-600 hover:text-gray-800 hover:bg-gray-50 rounded-md transition-colors"
                        >
                          Invoice
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Invoice Modal */}
      {showInvoice && selectedReport && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg max-w-4xl w-full mx-4 max-h-[90vh] overflow-y-auto">
            <div className="p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-lg font-medium text-gray-900">Invoice</h2>
                <button
                  onClick={() => setShowInvoice(false)}
                  className="text-gray-400 hover:text-gray-600"
                >
                  <X className="w-6 h-6" />
                </button>
              </div>
              <Invoice report={selectedReport} />
            </div>
          </div>
        </div>
      )}
    </AgentLayout>
  );
};

export default AgentReportsPage;